### ISSUE TITLE
Update Readme File

### ISSUE THREAD

**Issue by aplannersguide** [AtlantaRides/atlantarides.github.io#3]
It might be helpful to update the readme file to explain the project and how to contribute changes to the ordinance. [This is what I created](https://github.com/cityofchattanooga/Chattanooga-Open-Data-Executive-Order/blob/master/README.md) when crafting the github page for our city's open data policy.

**Comment by AtlantaRides** [comment]
I've added bullet points under the link. Just one link at this point so visitors see the scope and Beltline layout concept image, along with the ordinance input before they link to the city's 1st draft.

There is not currently a process to submit changes to the city ordinance that I am aware of, other than sending email to the individuals and city reps who attended the prior council meeting. If input is posted using the Issue tabs, I'll send email to the prior meeting attendees before the next city meeting on August 1st.
